### PR TITLE
Applied `cargo fmt` with the `.rustfmt.toml` from master branch.

### PR DESCRIPTION
**Pull request by ralfbiedert**
Here is the `cargo fmt` in isolation.

I just noticed there was a `.rustfmt.toml` on master, but not on next for some reason which got me confused initially. I moved it over, disabled `write_mode` which wasn't recognized anymore and applied it.

I don't have any strong feelings how the content should be formatted, I just think that _some_ formatting should be applied as otherwise it's hard to match that manually.

### CODE REVIEW

**Comment by Robbepop** [comment]
Can you please use the `rustfmt.toml` from here https://github.com/paritytech/ink/blob/master/.rustfmt.toml ?

Also I think we should add a formatting check to the Travis CI pipeline similar to how I did it for ink!:
`cargo fmt --verbose --all -- --check` (maybe leave away `--all` for Prophet)

**Comment by ralfbiedert** [comment]
Sure. What about 

- the `LICENSE_TEMPLATE`,
- `unstable_features = true`, which will require people to use nightly 
- and the `required_version` (currently gives `rustfmt version (1.3.0) doesn't match the required version (1.2.2)`)?

Also, the keys `fn_args_density` and `format_doc_comments` seem to be unknown (which might be due to `unstable_features` / the version mismatch).

**Comment by Robbepop** [comment]
> Sure. What about
> 
>     * the `LICENSE_TEMPLATE`,
> 
>     * `unstable_features = true`, which will require people to use nightly
> 
>     * and the `required_version` (currently gives `rustfmt version (1.3.0) doesn't match the required version (1.2.2)`)?
> 
> 
> Also, the keys `fn_args_density` and `format_doc_comments` seem to be unknown (which might be due to `unstable_features` / the version mismatch).

Thank you for the questions, sorry for forgetting to answer quickly.

We don't need a LICENSE_TEMPLATE for this project.
We also do not anticipate to use rustfmt unstable features, thanks for noting it!
Required version should also not be pinned for prophet.

**Comment by ralfbiedert** [comment]
Updated the fmt file.

**Comment by Robbepop** [comment]
Hmm, ... I _could_ go over the 8+k lines of code diff to prove that nothing went bad OR I put enough trust in you and especially rustfmt to just merge it.

I get the feeling that PRs with a size like these are always nightmares.

**Comment by ralfbiedert** [comment]
If you don't trust this you could just copy the rustfmt and apply it yourself on the previous commit ;)

**Comment by Robbepop** [comment]
Should be fine! Thank you for your work. :)

**Pull request merged**
